[package]
name = "governance"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "governance"

[dependencies]
anchor-lang = "0.28.0"
anchor-spl = "0.28.0"
pi-coin = { path = "../pi-coin" }

[dev-dependencies]
mocha = "10"
chai = "4"
