version: '3.8'
services:
  solanacore-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    environment:
      - SOLANA_ENDPOINT=https://api.mainnet-beta.solana.com # Example Solana RPC endpoint
    volumes:
      - ./api:/app
    networks:
      - solana-network
    depends_on:
      - redis # Optional, if your API uses Redis for caching
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - solana-network
networks:
  solana-network:
    driver: bridge
volumes:
  redis-data:
